openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /departments/:
    get:
      operationId: listDepartments
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Department'
          description: ''
      tags:
      - departments
  /departments/{id}/:
    get:
      operationId: retrieveDepartment
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0414\u0435\u043F\u0430\
          \u0440\u0442\u0430\u043C\u0435\u043D\u0442."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Department'
          description: ''
      tags:
      - departments
  /employees/:
    get:
      operationId: listEmployees
      description: ''
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: last_name
        required: false
        in: query
        description: last_name
        schema:
          type: string
      - name: department
        required: false
        in: query
        description: department
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=4
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=2
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Employee'
          description: ''
      tags:
      - employees
    post:
      operationId: createEmployee
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Employee'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Employee'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
          description: ''
      tags:
      - employees
  /employees/{id}/:
    get:
      operationId: retrieveEmployee
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0421\u043E\u0442\u0440\
          \u0443\u0434\u043D\u0438\u043A."
        schema:
          type: string
      - name: last_name
        required: false
        in: query
        description: last_name
        schema:
          type: string
      - name: department
        required: false
        in: query
        description: department
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
          description: ''
      tags:
      - employees
    put:
      operationId: updateEmployee
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0421\u043E\u0442\u0440\
          \u0443\u0434\u043D\u0438\u043A."
        schema:
          type: string
      - name: last_name
        required: false
        in: query
        description: last_name
        schema:
          type: string
      - name: department
        required: false
        in: query
        description: department
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Employee'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Employee'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
          description: ''
      tags:
      - employees
    patch:
      operationId: partialUpdateEmployee
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0421\u043E\u0442\u0440\
          \u0443\u0434\u043D\u0438\u043A."
        schema:
          type: string
      - name: last_name
        required: false
        in: query
        description: last_name
        schema:
          type: string
      - name: department
        required: false
        in: query
        description: department
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Employee'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Employee'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
          description: ''
      tags:
      - employees
    delete:
      operationId: destroyEmployee
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0421\u043E\u0442\u0440\
          \u0443\u0434\u043D\u0438\u043A."
        schema:
          type: string
      - name: last_name
        required: false
        in: query
        description: last_name
        schema:
          type: string
      - name: department
        required: false
        in: query
        description: department
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - employees
  /employees_by_dept/:
    get:
      operationId: listDepartments
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EmployeeByDept'
          description: ''
      tags:
      - employees-by-dept
    post:
      operationId: createDepartment
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeByDept'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/EmployeeByDept'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/EmployeeByDept'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeByDept'
          description: ''
      tags:
      - employees-by-dept
  /employees_by_dept/{id}/:
    get:
      operationId: retrieveDepartment
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0414\u0435\u043F\u0430\
          \u0440\u0442\u0430\u043C\u0435\u043D\u0442."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeByDept'
          description: ''
      tags:
      - employees-by-dept
    put:
      operationId: updateDepartment
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0414\u0435\u043F\u0430\
          \u0440\u0442\u0430\u043C\u0435\u043D\u0442."
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeByDept'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/EmployeeByDept'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/EmployeeByDept'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeByDept'
          description: ''
      tags:
      - employees-by-dept
    patch:
      operationId: partialUpdateDepartment
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0414\u0435\u043F\u0430\
          \u0440\u0442\u0430\u043C\u0435\u043D\u0442."
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeByDept'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/EmployeeByDept'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/EmployeeByDept'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeByDept'
          description: ''
      tags:
      - employees-by-dept
    delete:
      operationId: destroyDepartment
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0414\u0435\u043F\u0430\
          \u0440\u0442\u0430\u043C\u0435\u043D\u0442."
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - employees-by-dept
components:
  schemas:
    Department:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 150
        director:
          type: string
          readOnly: true
        employees_count:
          type: string
          readOnly: true
        total_salary:
          type: string
          readOnly: true
      required:
      - name
    Employee:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        last_name:
          type: string
          maxLength: 150
        first_name:
          type: string
          maxLength: 150
        surname:
          type: string
          maxLength: 150
        photo:
          type: string
          format: binary
        job_title:
          type: string
          maxLength: 150
        age:
          type: integer
          minimum: 18
        salary:
          type: integer
        department:
          type: integer
      required:
      - last_name
      - first_name
      - surname
      - job_title
      - age
      - salary
      - department
    EmployeeByDept:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 150
        director:
          type: string
          readOnly: true
        employee:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                readOnly: true
              last_name:
                type: string
                maxLength: 150
              first_name:
                type: string
                maxLength: 150
              surname:
                type: string
                maxLength: 150
              photo:
                type: string
                format: binary
              job_title:
                type: string
                maxLength: 150
              age:
                type: integer
                minimum: 18
              salary:
                type: integer
              department:
                type: integer
            required:
            - last_name
            - first_name
            - surname
            - job_title
            - age
            - salary
            - department
          readOnly: true
      required:
      - name
